/* Startup functional review. Production HTML, fresh contexts, invented words.
 * Controlled delays/errors below are test-only wrappers; no production hooks.
 * CARNET_BROWSERS / CARNET_RELEASE_HTML / runtime.cjs overrides are supported. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {pathToFileURL}=require('node:url'),{createHash}=require('node:crypto');
const paths=require('./paths.cjs'),out=path.join(paths.runRoot,'startup-review');fs.mkdirSync(out,{recursive:true});
process.env.DEBUG=[process.env.DEBUG,'pw:browser'].filter(Boolean).join(',');process.env.DEBUG_FILE=path.join(out,'browser.log');
const {launchBrowser}=require('./runtime.cjs'),KEY='FR_VOCAB_STARTUP_HINT_V1';
const html=fs.readFileSync(paths.releaseFile,'utf8');
assert.match(html,/data-bundled-source="startup\.js"/,'Build the startup candidate before this review');
assert.doesNotMatch(html,/<script[^>]+id=["']portable-state/,'Input must be a release, never a personal portable archive');
const formal=path.join(out,'candidate.html'),previewRoot=path.join(out,'source');fs.writeFileSync(formal,html);fs.cpSync(paths.sourceRoot,previewRoot,{recursive:true,filter:file=>!file.endsWith('.html')||['index.html','release-build.html'].includes(path.basename(file))});
const report={file:paths.releaseFile,frozenFile:formal,previewRoot,sha256:createHash('sha256').update(html).digest('hex'),checks:[],errors:[],samples:[],screenshots:[],videos:[],
 instrumentation:['Data delay holds the real load result; rejection is injected before load. A three-word invented return-user fixture is imported, validated and saved through production APIs in a fresh context.',
 'Scene delays hold the real mount Promise. Manual/automatic fallback runs the real useStaticFallback and releases that pending mount with its result. The manual-button case alone uses a paused Playwright clock so synchronous software WebGL preparation cannot consume its 3–6 second interaction window; the automatic fallback case retains real elapsed time. WebGL denial and image decode rejection are injected only in test pages.',
 'Visibility is simulated with document.hidden/visibilityState getters plus visibilitychange. This does not establish real background-tab or device behavior.',
 'The fast-controller fixture retains the actual built CSS, shell and startup script but removes unrelated scripts. It validates the under-200ms branch, not full-application performance.',
 'Storage, full-state getters, startup text setters and native Element.animate are observed. CSS zoom simulates 200% layout; it is not a native browser zoom or screen-reader test.'],
 reusedCoverage:{T22:'Existing release/guide-recovery/interaction browser suites',T25:'onboarding-settings-review copies',T26:'This suite startup plus onboarding-settings-review replay/scroll',T27:'This suite startup plus onboarding-settings-review unchanged guide text',T28:'onboarding-settings-review live preferences',T29:'startup-performance-review B/C comparison',T33:'Root final artifact/document review',T34:'Root complete Node/browser runners'},
 limits:['Playwright Chromium and WebKit are engine checks, not physical Safari/iOS, assistive technology, native zoom or audible speech verification. Reused suites are references, not additional passes counted here.', 'Raw src/index.html correctly refuses portable export because it is not bundled; portable preview export/reopen is checked through the generated src/release-build.html.', 'Chromium uses native offline mode. WebKit rejects even a blank local file with offline:true in this installed runtime, so its HTTP(S) requests are intercepted and aborted instead; any such request still fails this review. This does not simulate OS-level disconnection.']};
let browser,engine='',closing=false;const contexts=new Set();
function save(){fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));}
function pass(name,ids,details){report.checks.push({engine,name,ids,details});console.log('PASS',engine,name);save();}
function instrument(o){
 const p=window.__startupTest={loads:0,saves:0,fullReads:0,hintReads:0,hintWrites:[],stateWrites:0,sceneMounts:0,fallbacks:0,errors:[],editorial:[],countWrites:[],focus:[],textWrites:0,repeatedText:0,phases:[],ignore:false,holdScene:!!o.holdScene,hidden:!!o.hidden,failSave:false};
 const hintKey='FR_VOCAB_STARTUP_HINT_V1',nativeGet=Storage.prototype.getItem,nativeSet=Storage.prototype.setItem;
 if(o.hint!==undefined)nativeSet.call(localStorage,hintKey,typeof o.hint==='string'?o.hint:JSON.stringify(o.hint));
 if(o.corrupt)nativeSet.call(localStorage,'FR_VOCAB_APP_V4','{not a valid archive');
 Storage.prototype.getItem=function(key){if(key===hintKey)p.hintReads++;if(o.noStorage)throw new DOMException('Injected storage denial','SecurityError');return nativeGet.call(this,key);};
 Storage.prototype.setItem=function(key,value){if(key===hintKey)p.hintWrites.push(String(value));if(key==='FR_VOCAB_APP_V4')p.stateWrites++;if(o.noStorage)throw new DOMException('Injected storage denial','SecurityError');return nativeSet.call(this,key,value);};
 if(o.noIDB||o.noStorage)Object.defineProperty(indexedDB,'open',{configurable:true,value(){throw new DOMException('Injected IndexedDB denial','SecurityError');}});
 if(o.hidden!==undefined){Object.defineProperty(document,'hidden',{configurable:true,get:()=>p.hidden});Object.defineProperty(document,'visibilityState',{configurable:true,get:()=>p.hidden?'hidden':'visible'});p.setHidden=value=>{p.hidden=value;document.dispatchEvent(new Event('visibilitychange'));};}
 if(o.noWebGL){const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /webgl/i.test(type)?null:get.call(this,type,...args);};}
 if(o.badImage){const decode=HTMLImageElement.prototype.decode;HTMLImageElement.prototype.decode=function(...args){return this.classList.contains('carnet-scene-static')?Promise.reject(new Error('Injected static decode failure')):decode.apply(this,args);};}
 const text=Object.getOwnPropertyDescriptor(Node.prototype,'textContent');Object.defineProperty(Node.prototype,'textContent',{...text,set(value){if(this.nodeType===1&&this.matches('.startup-status')){p.textWrites++;if(text.get.call(this)===String(value??''))p.repeatedText++;}if(this.nodeType===1&&this.matches('.editorial-count-display'))p.countWrites.push({active:!!window.VocabStartup?.isActive(),value});text.set.call(this,value);}});
 const focus=HTMLElement.prototype.focus;HTMLElement.prototype.focus=function(...args){const relevant=this.closest('#startup-shell')||this.id==='carnet-title';if(relevant)p.focus.push({target:this.id||this.dataset.startupAction,stage:'before',inert:!!this.closest('[inert]'),active:document.activeElement.id});const result=focus.apply(this,args);if(relevant)p.focus.push({target:this.id||this.dataset.startupAction,stage:'after',active:document.activeElement.id});return result;};
 const animate=Element.prototype.animate;Element.prototype.animate=function(...args){if(this.matches('.editorial-line>span,.today-grid>.task-card,.today-bottom>.card'))p.editorial.push({className:this.className,active:!!window.VocabStartup?.isActive()});return animate.apply(this,args);};
 function intercept(name,fn){let value;Object.defineProperty(window,name,{configurable:true,get:()=>value,set:next=>{value=fn(next);}});}
 intercept('VocabData',D=>({...D,async load(...args){p.loads++;if(o.rejectData)throw new Error('Injected startup load failure');let result=await D.load(...args);
  if(o.returning&&!result.state.decks.length&&!result.blocked&&!sessionStorage.getItem('__startup_review_fixture_seeded')){let state=D.importEntries(result.state,[{french:'lueurfictive',meaning:'虚构微光',pos:'n.f.',example:'Une lueur fictive apparaît.',exampleZh:'一道虚构微光出现。'},{french:'jardinfictif',meaning:'虚构花园',pos:'n.m.'},{french:'cheminfictif',meaning:'虚构小路',pos:'n.m.'}],{name:'Invented startup review',mode:'new'}).state;state.settings={...state.settings,onboardingComplete:true,autoWord:false,autoExample:false,...o.settings};state.settings.studyDeckIds=state.decks.map(d=>d.id);VocabEngine.ensureState(state);result=await D.save(state);p.fixture=JSON.parse(JSON.stringify(result.state));sessionStorage.setItem('__startup_review_fixture_seeded','1');}
  p.loaded={backend:result.backend,blocked:!!result.blocked,persistent:result.persistent};if(o.holdData)await new Promise(resolve=>p.releaseData=resolve);return result;
 },async save(...args){p.saves++;if(p.failSave)throw new Error('Injected setting save failure');return D.save(...args);}}));
 intercept('VocabApp',app=>{const get=app.getState;app.getState=function(...args){if(!p.ignore)p.fullReads++;return get.apply(this,args);};return app;});
 intercept('VocabStartup',S=>({...S,setPhase(...args){p.phases.push(args[0]);return S.setPhase(...args);},markViewReady(value){if(o.holdView){p.view=value;p.releaseView=()=>S.markViewReady(value);return;}return S.markViewReady(value);}}));
 intercept('VocabCarnetScene',S=>{const mount=S.mount,fallback=S.useStaticFallback,destroy=S.destroy;let release,progress;
  S.mount=function(host,options){p.sceneMounts++;progress=options?.onProgress;const original=mount.call(this,host,options);if(!p.holdScene)return original;p.realScene=original;p.realSceneSettled=null;Promise.resolve(original).then(value=>p.realSceneSettled=value,()=>{});return new Promise(resolve=>{release=resolve;p.releaseScene=()=>Promise.resolve(original).then(resolve);});};
  S.useStaticFallback=function(...args){p.fallbacks++;const result=fallback.apply(this,args);Promise.resolve(result).then(value=>release?.(value),()=>{});return result;};
  S.destroy=function(...args){const result=destroy.apply(this,args);release?.({backend:'disposed'});return result;};p.lateProgress=()=>progress?.({phase:'complete'});return S;});
 p.inspect=fn=>{p.ignore=true;try{return fn();}finally{p.ignore=false;}};
 if(o.noEndEvents){const add=EventTarget.prototype.addEventListener;EventTarget.prototype.addEventListener=function(type,...args){if(this.id==='startup-shell'&&['transitionend','animationend'].includes(type))return;return add.call(this,type,...args);};}
}
async function open(o={},file=formal){
 const context=await browser.newContext({viewport:o.viewport||{width:1440,height:900},colorScheme:o.colorScheme||'light',reducedMotion:o.reduce?'reduce':'no-preference',javaScriptEnabled:o.js!==false,acceptDownloads:true,offline:engine==='Chromium',...(o.video&&process.env.CARNET_STARTUP_VIDEO==='1'?{recordVideo:{dir:out,size:{width:960,height:600}}}:{})});contexts.add(context);await context.route(/^https?:/,route=>route.abort());await context.addInitScript(instrument,o);const page=await context.newPage();page.setDefaultTimeout(20000);if(o.manualClock){const time=Date.UTC(2026,0,1);await page.clock.install({time});await page.clock.pauseAt(time+1000);}
 const meta={engine,file,options:o,closing:false};page.__meta=meta;
 page.on('pageerror',error=>{report.errors.push({engine,file,message:error.message,expected:!!o.rejectData&&/Injected startup load failure/.test(error.message)});});
 page.on('crash',()=>report.errors.push({engine,event:'page crash',expected:false}));
 page.on('close',()=>{if(!meta.closing&&!closing)report.errors.push({engine,event:'unexpected page close',expected:false});});
 page.on('request',request=>{if(/^https?:/.test(request.url()))report.errors.push({engine,event:'network request',url:request.url(),expected:false});});
 await page.goto(pathToFileURL(file).href,{waitUntil:'domcontentloaded'});return page;
}
async function close(page){page.__meta.closing=true;contexts.delete(page.context());const video=page.video();await page.context().close();if(video){const file=engine+'-'+page.__meta.options.video+'.webm';await video.saveAs(path.join(out,file));report.videos.push(file);}}
async function wait(page,predicate,timeout=20000){await page.waitForFunction(predicate,null,{timeout,polling:50});}
async function clockUntil(page,predicate,budget=3000){for(let elapsed=0;elapsed<budget;elapsed+=100){if(await page.evaluate(predicate))return;await page.clock.runFor(100);}assert.ok(await page.evaluate(predicate),'Controlled-clock condition did not settle within '+budget+'ms');}
async function removed(page){await wait(page,()=>window.VocabStartup?.getState().removed);assert.equal(await page.locator('#startup-shell').count(),0);assert.equal(await page.locator('.startup-active,[data-startup-inert]').count(),0);}
async function probe(page){return page.evaluate(()=>{const p=__startupTest;return {loads:p.loads,saves:p.saves,fullReads:p.fullReads,hintReads:p.hintReads,hintWrites:p.hintWrites,stateWrites:p.stateWrites,sceneMounts:p.sceneMounts,fallbacks:p.fallbacks,loaded:p.loaded,editorial:p.editorial,countWrites:p.countWrites,textWrites:p.textWrites,repeatedText:p.repeatedText,state:VocabStartup.getState()};});}
async function records(page){return page.evaluate(()=>__startupTest.inspect(()=>{const s=VocabApp.getState();return {decks:s.decks,cards:s.cards,skills:s.skills,contexts:s.contexts,events:s.events,eventArchive:s.eventArchive,session:s.session,settings:s.settings};}));}
const hint=(design='classic',mode='light',language='zh',motion='immersive')=>({version:1,design,mode,language,motion});
async function basic(){
 let page=await open({reduce:true});await removed(page);let p=await probe(page);assert.equal(p.loads,1);assert.equal(p.fullReads,0);assert.equal(p.state.target,'journey');let s=await records(page);assert.equal(s.decks.length,0);assert.equal(s.settings.onboardingComplete,false);assert.equal(s.events.length,0);assert.equal(p.repeatedText,0);await close(page);
 page=await open({returning:true,video:'returning-startup'});await removed(page);p=await probe(page);assert.equal(p.loads,1);assert.equal(p.sceneMounts,0);assert.equal(p.state.target,'today');assert.equal(p.fullReads,0);s=await records(page);const before=s;await page.evaluate(()=>{VocabStartup.setPhase('scene');VocabStartup.markDataReady();VocabStartup.markViewReady({target:'journey',backend:'webgl'});VocabStartup.fail(new Error('late ignored failure'));dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));});assert.deepEqual(await records(page),before);assert.equal(await page.locator('#startup-shell').count(),0);report.samples.push({engine,normal:p});await page.reload();await removed(page);assert.equal((await probe(page)).hintWrites.length,0);assert.deepEqual(await records(page),before);await close(page);pass('Fresh and returning routes retain data; startup reads no full archive and removal is terminal',['T01','T02','T16','T18','T26','T27']);
}
function controllerFile(fast=false){const name=path.join(out,fast?'controller-fast.html':'controller.html');let content=html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,tag=>tag.includes('data-bundled-source="startup.js"')?tag:'');if(fast)content=content.replace('</body>','<script>window.__fastBefore=VocabStartup.getState();VocabStartup.markDataReady();VocabStartup.markViewReady({target:"today"});window.__fastAfter=VocabStartup.getState();<\/script></body>');fs.writeFileSync(name,content);return name;}
async function controller(){
 let page=await open({video:'controller-fast'},controllerFile(true));await removed(page);const fast=await page.evaluate(()=>({before:__fastBefore,after:__fastAfter}));assert.equal(fast.before.indicatorVisible,false);assert.equal(fast.after.indicatorVisible,false);assert.equal(fast.after.removed,true);report.samples.push({engine,fastController:fast});await close(page);
 page=await open({noEndEvents:true},controllerFile());await wait(page,()=>VocabStartup.getState().indicatorVisible);const a11y=await page.evaluate(()=>({statuses:document.querySelectorAll('#startup-shell [role=status]').length,live:document.querySelector('.startup-status').getAttribute('aria-live'),motto:document.querySelector('.startup-motto').lang,decor:document.querySelector('.startup-ink').getAttribute('aria-hidden'),buttons:[...document.querySelectorAll('#startup-shell button')].filter(b=>!b.hidden).length,progress:document.querySelectorAll('#startup-shell [aria-valuenow]').length,bodyInert:document.body.inert,busy:!!document.querySelector('.startup-status').closest('[aria-busy=true]')}));assert.deepEqual(a11y,{statuses:1,live:'polite',motto:'fr',decor:'true',buttons:0,progress:0,bodyInert:false,busy:false});
 for(const [lang,re]of [['en-US',/Opening/],['fr-CA',/Ouverture/],['zh-CN',/正在打开/]]){await page.evaluate(lang=>document.documentElement.lang=lang,lang);await wait(page,()=>!!document.querySelector('.startup-status').textContent);assert.match(await page.locator('.startup-status').innerText(),re);}
 await page.evaluate(()=>{__startupTest.repeatedText=0;for(let i=0;i<30;i++)VocabStartup.setPhase('opening');VocabStartup.markViewReady({target:'journey',backend:'disposed'});});assert.equal((await probe(page)).state.viewReady,false);assert.equal((await probe(page)).repeatedText,0);
 const generations=await page.evaluate(async()=>{const pending=[];window.VocabCarnetScene={mount(){},destroy(){},useStaticFallback(){return new Promise((resolve,reject)=>pending.push({resolve,reject}));}};VocabStartup.markDataReady();VocabStartup.setPhase('scene',{sceneEpoch:1});const old=VocabStartup.requestSceneFallback();VocabStartup.setPhase('scene',{sceneEpoch:1});await VocabStartup.requestSceneFallback();const duplicate=pending.length;VocabStartup.setPhase('scene',{sceneEpoch:2});const current=VocabStartup.requestSceneFallback();const afterNew=pending.length;pending[0].reject(new Error('Injected stale scene rejection'));await old;const staleIgnored=!VocabStartup.getState().failed;pending[1]?.resolve({backend:'static'});await current;return {duplicate,afterNew,staleIgnored};});assert.deepEqual(generations,{duplicate:1,afterNew:2,staleIgnored:true});
 await page.evaluate(()=>{VocabStartup.markViewReady({target:'today'});});await removed(page);await close(page);pass('Actual controller fast branch, multilingual semantics, idempotence and event-free exit cleanup',['T02','T14','T16','T17','T18','T27']);
}
async function dataFailures(){
 let page=await open({returning:true,holdData:true,video:'delayed-startup'});await wait(page,()=>!!__startupTest.releaseData);assert.equal((await probe(page)).state.dataReady,false);await wait(page,()=>VocabStartup.getState().indicatorVisible);assert.match(await page.locator('.startup-status').innerText(),/读取/);await page.evaluate(()=>__startupTest.releaseData());await removed(page);assert.equal((await probe(page)).sceneMounts,0);await close(page);
 page=await open({holdData:true,reduce:true});await wait(page,()=>!!__startupTest.releaseData);await page.locator('[data-startup-action=help]').waitFor({state:'visible',timeout:15000});const p=await probe(page);assert.equal(p.loads,1);assert.equal(p.state.dataReady,false);assert.equal(p.state.failed,false);await page.locator('[data-startup-action=help]').click();assert.ok(await page.locator('.startup-help').isVisible());await page.locator('[data-startup-action=help]').focus();await page.evaluate(()=>__startupTest.releaseData());await removed(page);const focus=await page.evaluate(()=>({active:document.activeElement.outerHTML.slice(0,300),calls:__startupTest.focus,target:document.querySelector('#carnet-title')?.outerHTML,ancestors:[...document.querySelectorAll('#carnet-story [inert],#carnet-story[inert]')].map(el=>el.className)}));report.samples.push({engine,handoffFocus:focus});assert.equal(await page.evaluate(()=>document.activeElement.id),'carnet-title',JSON.stringify(focus));assert.equal((await probe(page)).loads,1);await close(page);
 page=await open({rejectData:true});await wait(page,()=>VocabStartup.getState().failed);assert.ok(await page.locator('[data-startup-action=reload]').isVisible());assert.equal((await probe(page)).state.dataReady,false);assert.equal((await probe(page)).loads,1);await close(page);pass('Delayed, still-pending and rejected loads retain a single data read and truthful recovery actions',['T03','T10']);
}
async function storage(){
 for(const [options,backend]of [[{noIDB:true},'localStorage'],[{noStorage:true},'memory'],[{noIDB:true,corrupt:true},'localStorage']]){const page=await open({...options,reduce:true});await removed(page);const p=await probe(page);assert.equal(p.loaded.backend,backend);assert.equal(p.loads,1);if(options.corrupt){assert.equal(p.loaded.blocked,true);assert.equal(p.state.target,'today');assert.equal(p.sceneMounts,0);assert.equal(p.stateWrites,0);assert.equal(p.hintWrites.length,0);assert.equal(await page.evaluate(()=>localStorage.getItem('FR_VOCAB_APP_V4')),'{not a valid archive');}else{assert.equal(p.state.target,'journey');assert.equal(p.loaded.persistent,backend!=='memory');}assert.match(await page.locator('#app').textContent(),options.corrupt?/停止覆盖|无法校验/:options.noStorage?/临时|无法保存/:/备用存储/);await close(page);}pass('Unavailable and corrupt storage follows real fallback/recovery behavior without overwriting data',['T07','T08','T09']);
}
async function scenes(){
 let page=await open({holdScene:true,manualClock:true});await clockUntil(page,()=>!!__startupTest.realSceneSettled);const untilSlow=await page.evaluate(()=>Math.max(0,VocabStartup.TIMES.SLOW_NOTICE_MS-(performance.now()-VocabStartup.getState().startedAt)));await page.clock.runFor(untilSlow);assert.equal((await probe(page)).fallbacks,0);await page.locator('[data-startup-action=fallback]').waitFor({state:'visible'});assert.equal(await page.locator('.carnet-loading').isVisible(),false);const pref=await page.evaluate(()=>VocabApp.getSettings().carnetMotion);await page.evaluate(()=>{document.querySelector('[data-startup-action=fallback]').click();document.querySelector('[data-startup-action=fallback]').click();});assert.equal((await probe(page)).fallbacks,1);await clockUntil(page,()=>VocabStartup.getState().removed);await removed(page);let p=await probe(page);report.samples.push({engine,manualFallback:{clock:'paused Playwright clock; native scene and fallback retained',fallbacks:p.fallbacks,backend:p.state.backend,scene:await page.evaluate(()=>__startupTest.realSceneSettled)}});assert.equal(p.fallbacks,1);assert.ok(['static','simplified'].includes(p.state.backend));assert.equal(await page.evaluate(()=>VocabApp.getSettings().carnetMotion),pref);await close(page);
 page=await open({holdScene:true,hidden:true,reduce:true});await wait(page,()=>__startupTest.sceneMounts===1);await page.waitForTimeout(6500);assert.equal((await probe(page)).fallbacks,0);await page.evaluate(()=>__startupTest.setHidden(false));await removed(page);p=await probe(page);assert.equal(p.fallbacks,1);assert.ok(['static','simplified'].includes(p.state.backend));await close(page);
 page=await open({holdScene:true,reduce:true});await wait(page,()=>__startupTest.sceneMounts===1);await page.evaluate(()=>{dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));});await wait(page,()=>__startupTest.sceneMounts===2);assert.equal((await probe(page)).state.viewReady,false);await page.evaluate(()=>__startupTest.releaseScene());await removed(page);assert.equal((await probe(page)).state.target,'journey');await close(page);
 for(const badImage of [false,true]){page=await open({noWebGL:true,badImage,reduce:true});await removed(page);p=await probe(page);assert.equal(p.state.backend,badImage?'simplified':'static');if(!badImage)assert.ok(await page.locator('.carnet-scene-static').evaluate(img=>img.complete&&img.naturalWidth>0));assert.ok(await page.locator('#carnet-title').isVisible());await page.locator('.caption-actions [data-carnet=chapter][data-chapter-target=\"1\"]').click();await wait(page,()=>document.body.dataset.carnetChapter==='1');await close(page);}pass('Real scene fallback is single-use, visibility-aware and readable after WebGL/image failure',['T04','T05','T06','T15','T17']);
}
async function cache(){
 const invalid=['{bad json','x'.repeat(1025),{...hint('verdure','dark'),extra:'not allowed'},{...hint('verdure','dark'),version:2},{...hint(),design:'unknown'}];
 for(const raw of invalid){const page=await open({hint:raw,holdData:true});await wait(page,()=>!!__startupTest.releaseData);assert.equal(await page.evaluate(()=>document.documentElement.dataset.designTheme),'classic');assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'light');await close(page);}
 let page=await open({returning:true,holdData:true,hint:hint('verdure','dark','fr'),settings:{designTheme:'atelier',theme:'light',language:'en'},reduce:true});await wait(page,()=>!!__startupTest.releaseData);assert.equal(await page.evaluate(()=>document.documentElement.dataset.designTheme),'verdure');await page.evaluate(()=>__startupTest.releaseData());await removed(page);assert.equal(await page.evaluate(()=>document.documentElement.dataset.designTheme),'atelier');assert.equal(await page.evaluate(()=>document.documentElement.lang),'en');let p=await probe(page);const writes=p.hintWrites.length;await page.evaluate(()=>{for(let i=0;i<20;i++)VocabStartup.syncHint(VocabApp.getSettings());});assert.equal((await probe(page)).hintWrites.length,writes);const stored=JSON.parse(p.hintWrites.at(-1));assert.deepEqual(Object.keys(stored).sort(),['design','language','mode','motion','version']);assert.ok(Buffer.byteLength(JSON.stringify(stored))<=1024);
 await page.evaluate(()=>VocabCarnetReview.show('settings'));await page.locator('#settings-form [name=language]').selectOption('fr');assert.equal((await probe(page)).hintWrites.length,writes);await page.evaluate(()=>__startupTest.failSave=true);assert.equal(await page.evaluate(()=>VocabCarnetProduct.setAppearance({design:'verdure'})),false);assert.equal((await probe(page)).hintWrites.length,writes);await page.evaluate(()=>__startupTest.failSave=false);assert.equal(await page.evaluate(()=>VocabCarnetProduct.setAppearance({design:'verdure'})),true);assert.equal(JSON.parse((await probe(page)).hintWrites.at(-1)).design,'verdure');
 const other=await page.context().newPage();other.on('pageerror',error=>report.errors.push({engine,message:error.message,expected:false}));await other.goto(pathToFileURL(formal).href,{waitUntil:'domcontentloaded'});await wait(other,()=>!!__startupTest.releaseData);await other.evaluate(()=>__startupTest.releaseData());await removed(other);await other.evaluate(()=>{window.__hintEvents=0;addEventListener('storage',event=>{if(event.key==='FR_VOCAB_STARTUP_HINT_V1')__hintEvents++;});});await page.evaluate(()=>VocabStartup.syncHint({...VocabApp.getSettings(),theme:'dark'}));await wait(other,()=>__hintEvents>0);assert.doesNotMatch(await other.locator('#toast').textContent(),/另一页面更新|Another tab changed|Un autre onglet a changé/);report.samples.push({engine,pureHintCrossPageEvents:await other.evaluate(()=>__hintEvents)});await other.close();await page.evaluate(()=>VocabStartup.syncHint(VocabApp.getSettings()));
 await page.evaluate(()=>localStorage.setItem('unrelated-startup-test','keep'));await page.evaluate(()=>VocabLocalReset.execute({confirmed:true}));assert.equal(await page.evaluate(key=>localStorage.getItem(key),KEY),null);assert.equal(await page.evaluate(()=>localStorage.getItem('unrelated-startup-test')),'keep');await page.reload();await wait(page,()=>!!__startupTest.releaseData);await page.evaluate(()=>__startupTest.releaseData());await removed(page);assert.equal((await probe(page)).state.target,'journey');assert.equal(await page.evaluate(()=>VocabApp.getSettings().designTheme),'classic');await close(page);
 page=await open({hint:hint('classic','system'),holdData:true,colorScheme:'dark'});await wait(page,()=>!!__startupTest.releaseData);assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'dark');await page.emulateMedia({colorScheme:'light'});await wait(page,()=>document.documentElement.dataset.theme==='light');await close(page);pass('Appearance hints validate, reconcile, deduplicate, follow system mode and clear only on explicit reset',['T12','T13','T21','T31']);
}
async function accessibilityAndMotion(){
 const page=await open({returning:true,holdView:true,settings:{motionMode:'standard',carnetMotion:'immersive'}});await wait(page,()=>!!__startupTest.releaseView);await wait(page,()=>VocabStartup.getState().indicatorVisible);let p=await probe(page);assert.equal(p.editorial.length,0);assert.equal(p.countWrites.length,0);assert.equal(await page.locator('#app').evaluate(el=>el.inert),true);assert.equal(await page.evaluate(()=>document.body.inert),false);assert.ok(await page.locator('#app').evaluate(el=>el.getBoundingClientRect().width)>0);
 await page.evaluate(()=>{window.__mainBefore=document.querySelector('#app .main');const el=document.createElement('button');el.id='unrelated-inert-test';el.inert=true;document.body.append(el);});await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>!!document.activeElement.closest('#app')),false);await page.evaluate(()=>__startupTest.releaseView());await removed(page);await wait(page,()=>__startupTest.editorial.length>0&&__startupTest.countWrites.length>0);p=await probe(page);assert.ok(p.editorial.every(a=>!a.active));assert.ok(p.countWrites.every(a=>!a.active));assert.equal(await page.evaluate(()=>__mainBefore===document.querySelector('#app .main')),true);assert.equal(await page.locator('#unrelated-inert-test').evaluate(el=>el.inert),true);const count=p.editorial.length;await page.evaluate(()=>{VocabEditorialMotion.refresh('today');VocabEditorialMotion.refresh('today');});await page.waitForTimeout(200);assert.equal((await probe(page)).editorial.length,count);await close(page);
 const reduced=await open({returning:true,holdView:true,reduce:true});await wait(reduced,()=>!!__startupTest.releaseView);await wait(reduced,()=>VocabStartup.getState().indicatorVisible);assert.equal(await reduced.locator('.startup-ink').evaluate(el=>getComputedStyle(el).animationName),'none');await reduced.evaluate(()=>__startupTest.releaseView());await removed(reduced);assert.equal((await probe(reduced)).editorial.length,0);await close(reduced);pass('Underlying UI remains laid out but inert; home entrance waits for handoff and runs once; reduced motion stays still',['T14','T16','T30']);
}
async function replay(){
 const page=await open({returning:true,reduce:true});await removed(page);await page.evaluate(()=>{__startupTest.holdScene=true;VocabCarnetReview.show('journey');});await wait(page,()=>__startupTest.sceneMounts===1);assert.equal(await page.locator('#startup-shell').count(),0);assert.ok(await page.locator('.carnet-loading').isVisible());assert.doesNotMatch(await page.locator('.carnet-loading').innerText(),/\d+\s*%/);await page.evaluate(()=>document.documentElement.lang='fr-CA');assert.match(await page.locator('.carnet-loading').innerText(),/Préparation/);await page.evaluate(()=>{dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));});await wait(page,()=>__startupTest.sceneMounts===2);assert.equal(await page.locator('#startup-shell').count(),0);assert.ok(await page.locator('.carnet-loading').isVisible());await page.evaluate(()=>__startupTest.releaseScene());await wait(page,()=>document.querySelector('.carnet-loading').hidden);await page.evaluate(()=>VocabCarnetReview.show('today'));await page.evaluate(()=>{__startupTest.lateProgress();__startupTest.releaseScene();});assert.equal(await page.locator('#startup-shell').count(),0);assert.equal(await page.locator('.carnet-loading').isVisible(),false);assert.equal((await probe(page)).fullReads,0);await close(page);pass('Guide replay uses a local status and ignores canceled scene progress without resplashing',['T17','T18','T26']);
}
async function portable(){
 const page=await open({returning:true,reduce:true,settings:{designTheme:'verdure',theme:'dark',language:'fr'}});await removed(page);const before=await records(page);await page.evaluate(()=>VocabCarnetReview.show('settings'));const pending=page.waitForEvent('download');await page.locator('[data-action=portable]').evaluate(el=>el.click());const download=await pending,file=path.join(out,engine+'-portable.html');await download.saveAs(file);assert.ok(download.suggestedFilename().includes(paths.releaseConfig.version));assert.equal(await page.locator('#startup-shell').count(),0);
 const exported=fs.readFileSync(file,'utf8');assert.equal((exported.match(/id="startup-shell"/g)||[]).length,1);assert.match(exported,/data-startup-hint=/);assert.doesNotMatch(exported,/<[^>]+class="[^"]*startup-(?:leaving|waiting|static)/);assert.doesNotMatch(exported,/data-startup-inert=/);const reopened=await open({holdView:true,reduce:true},file);await wait(reopened,()=>!!__startupTest.releaseView);assert.equal(await reopened.locator('dialog[open]').count(),0);await reopened.evaluate(()=>__startupTest.releaseView());await removed(reopened);assert.deepEqual(await records(reopened),before);assert.equal(await reopened.evaluate(()=>VOCAB_RELEASE),paths.releaseConfig.version);await reopened.reload();await wait(reopened,()=>!!__startupTest.releaseView);assert.equal(await reopened.locator('dialog[open]').count(),0);await reopened.evaluate(()=>__startupTest.releaseView());await removed(reopened);await reopened.locator('#modal[open]').waitFor();assert.equal(await reopened.locator('#app').evaluate(el=>el.inert),false);await reopened.locator('#modal [data-action=close]').click();assert.deepEqual(await records(reopened),before);await close(reopened);
 await page.reload();await removed(page);await close(page);
 const preview=await open({reduce:true},path.join(previewRoot,'index.html'));await removed(preview);const p=await probe(preview);assert.equal(p.hintReads,0);assert.equal(p.hintWrites.length,0);assert.equal(await preview.evaluate(()=>CARNET_PREVIEW),true);await preview.evaluate(()=>VocabCarnetReview.show('settings'));await preview.locator('[data-action=portable]').evaluate(el=>el.click());await wait(preview,()=>/单文件正式版本|standalone release|HTML autonome/.test(document.querySelector('#toast').textContent));await close(preview);
 const bundled=await open({reduce:true},path.join(previewRoot,'release-build.html'));await removed(bundled);const previewBefore=await records(bundled);await bundled.evaluate(()=>VocabCarnetReview.show('settings'));const previewPending=bundled.waitForEvent('download');await bundled.locator('[data-action=portable]').evaluate(el=>el.click());const previewDownload=await previewPending,previewFile=path.join(out,engine+'-preview-portable.html');await previewDownload.saveAs(previewFile);const previewOpened=await open({reduce:true},previewFile);await removed(previewOpened);assert.deepEqual(await records(previewOpened),previewBefore);assert.equal((await probe(previewOpened)).hintReads,0);assert.equal((await probe(previewOpened)).hintWrites.length,0);assert.equal(await previewOpened.evaluate(()=>CARNET_PREVIEW),true);await close(previewOpened);await close(bundled);pass('Actual exported portable page recreates one clean startup shell and preserves data; preview avoids the formal hint key',['T19','T20','T32']);
}
async function visual(){
 if(engine!=='Chromium')return;
 for(const design of ['classic','atelier','verdure'])for(const mode of ['light','dark'])for(const viewport of [{width:1440,height:900},{width:390,height:844}]){const page=await open({hint:hint(design,mode),holdData:true,viewport});await wait(page,()=>VocabStartup.getState().indicatorVisible);const file=engine+'-'+design+'-'+mode+'-'+viewport.width+'.png';await page.screenshot({path:path.join(out,file)});report.screenshots.push(file);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await close(page);}
 for(const viewport of [{width:320,height:568},{width:844,height:390}]){const page=await open({holdData:true,viewport});await wait(page,()=>VocabStartup.getState().indicatorVisible);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const file=engine+'-narrow-'+viewport.width+'.png';await page.screenshot({path:path.join(out,file)});report.screenshots.push(file);await close(page);}
 const page=await open({holdData:true,viewport:{width:800,height:600}});await page.evaluate(()=>document.documentElement.style.zoom='2');await wait(page,()=>VocabStartup.getState().indicatorVisible);assert.equal(await page.locator('.startup-brand').evaluate(el=>el.getBoundingClientRect().width<=innerWidth),true);await page.locator('#startup-shell').evaluate(el=>el.scrollTop=el.scrollHeight);assert.equal(await page.locator('.startup-status').evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}),true);const file='Chromium-css-zoom-200.png';await page.screenshot({path:path.join(out,file)});report.screenshots.push(file);await close(page);pass('Six appearances at desktop/mobile plus compact, landscape and simulated 200% layout',['T11']);
}
async function noScript(){const page=await open({js:false});assert.ok(await page.locator('#startup-shell noscript').isVisible());assert.match(await page.locator('#startup-shell noscript').innerText(),/JavaScript/);assert.equal(await page.locator('.startup-ink').evaluate(el=>getComputedStyle(el).animationName),'none');await close(page);pass('No-JavaScript message remains visible; local files need no network requests',['T23','T24']);}
(async()=>{try{for(engine of (process.env.CARNET_BROWSERS||'Chromium,WebKit').split(',').map(x=>x.trim())){closing=false;browser=await launchBrowser(engine);browser.on('disconnected',()=>{if(!closing)report.errors.push({engine,event:'unexpected browser disconnect',expected:false});});for(const test of [basic,controller,dataFailures,storage,scenes,cache,accessibilityAndMotion,replay,portable,visual,noScript])await test();closing=true;await browser.close();browser=null;}assert.deepEqual(report.errors.filter(e=>!e.expected),[]);save();console.log('Startup review passed:',report.checks.length,'grouped checks; results',out);}catch(error){report.failure=error.stack;save();console.error(error);process.exitCode=1;}finally{closing=true;for(const context of contexts)await context.close().catch(()=>{});if(browser)await browser.close().catch(()=>{});save();}})();
