/* Review-only preview. The original validator, import and learning algorithms
   remain in use; every data/media storage boundary below is memory-only. */
(function (host) {
  'use strict';
  if (host.CARNET_PREVIEW !== true) return;
  const originalData = host.VocabData, originalAudio = host.AudioKit, engine = host.VocabEngine;
  if (!originalData || !originalAudio || !engine || !host.VocabSeed) throw new Error('预览模块的加载顺序不完整。');
  const copy = value => JSON.parse(JSON.stringify(value));
  const freshId = prefix => prefix + '-' + (host.crypto?.randomUUID?.() || Date.now().toString(36) + Math.random().toString(36).slice(2));
  const audit = { backend:'memory', preview:true, dataLoads:0, dataSaves:0, snapshotReads:0, mediaReads:0, mediaWrites:0, originalStorageCalls:0 };
  const listeners = new Set(), media = new Map();
  let previous = null, app = null, mediaQueue = Promise.resolve(), appearanceQueue = Promise.resolve(), mediaPlayback = null;
  let motion = 'immersive', resolveReady;
  const ready = new Promise(resolve => { resolveReady = resolve; });
  function makeFixture() {
    const result = originalData.importEntries(originalData.fresh(), host.VocabSeed, { name:'示例词表 · 日常法语', mode:'new' });
    const next = result.state, deck = next.decks.find(item => item.id === result.deckId);
    deck.words.forEach((word, index) => {
      const entry = host.VocabSeed[index];
      if (entry.contexts) next.contexts[word.id] = copy(entry.contexts).map((context, i) => ({ ...context, id:freshId('preview-example'), favorite:i === 0 && index < 6, origin:context.type === 'tts' && context.text === entry.example && context.translation === entry.exampleZh ? 'default' : 'custom' }));
    });
    next.settings.onboardingComplete = true;
    next.settings.autoWord = next.settings.autoExample = next.settings.listening = false;
    engine.ensureState(next);
    // A small, explicitly synthetic history is generated by the unchanged engine.
    // No scores or cards are manufactured by the preview renderer.
    const past = Date.now() - 3 * engine.DAY;
    engine.start(next, 'learn', { wordIds:deck.words.slice(0, 3).map(word => word.id), limit:3, ignoreGoal:true }, past);
    for (let count = 0; count < 80; count++) {
      const current = engine.current(next);
      if (!current || current.kind === 'summary') break;
      if (['choice','listening-choice'].includes(current.kind)) engine.answer(next, {choice:current.word.id}, past + count * 1000);
      else if (current.kind === 'recall') { engine.reveal(next); engine.answer(next, {rating:3}, past + count * 1000); }
      else if (current.task === 'exposure') engine.reveal(next);
      engine.next(next, past + count * 1000);
    }
    engine.finish(next);
    return originalData.validate(next);
  }
  let memory = makeFixture();
  const originalFixture = copy(memory);
  function result() { return {state:copy(memory), persistent:true, preview:true, backend:'memory', warning:'', blocked:false}; }
  async function load() { audit.dataLoads++; return result(); }
  async function save(value, options = {}) {
    const candidate = originalData.validate(value), expected = options.expectedRevision ?? value.revision;
    if (memory.revision !== expected) { const error = new Error('本次预览已更新，请重试。'); error.code = 'REVISION_CONFLICT'; throw error; }
    if (options.snapshot) previous = {id:'previous',savedAt:Date.now(),state:copy(memory)};
    candidate.revision = memory.revision + 1; memory = candidate; audit.dataSaves++;
    for (const listener of listeners) { try { listener({revision:memory.revision,backend:'memory',preview:true}); } catch (_) {} }
    return result();
  }
  async function listSnapshots() { audit.snapshotReads++; return previous ? [copy(previous)] : []; }
  async function restoreSnapshot(id, expectedRevision) {
    const item = (await listSnapshots()).find(snapshot => snapshot.id === id);
    if (!item) throw new Error('本次预览没有这份快照。');
    const next = originalData.migrate(item.state); next.revision = expectedRevision;
    return save(next, {expectedRevision,snapshot:true});
  }
  host.VocabData = Object.freeze({...originalData, load, save, listSnapshots, restoreSnapshot, subscribe(listener) { listeners.add(listener); return () => listeners.delete(listener); }});

  // Media remains usable, including import/restore/export, but no original
  // method with a storage path is allowed through to AudioKit's database.
  const TYPES = new Set(['audio/mpeg','audio/mp3','audio/mp4','audio/x-m4a','audio/aac','audio/wav','audio/wave','audio/x-wav','audio/ogg','application/ogg','audio/opus','audio/flac','audio/x-flac','audio/webm']);
  const builtins = () => Array.isArray(host.VocabBuiltinMedia) ? host.VocabBuiltinMedia : [];
  const text = (value, limit = 2000) => String(value || '').trim().slice(0, limit);
  function metadata(context) {
    const data = {};
    for (const key of ['source','author','license','licenseUrl','sourceUrl','text','translation']) data[key] = text(context[key]);
    for (const key of ['sourceUrl','licenseUrl']) if (data[key]) data[key] = originalAudio.safeURL(data[key]);
    return data;
  }
  function requireRights(context) { if (!text(context.source) || !text(context.license)) throw new Error('请先填写音频来源及许可说明。'); metadata(context); }
  async function validateBlob(blob, name = '') {
    if (!blob || typeof blob.arrayBuffer !== 'function' || !Number.isFinite(blob.size) || !blob.size) throw new Error('请选择有效的音频文件。');
    if (blob.size > originalAudio.MAX_FILE) throw new Error('单个音频不能超过 15 MB。');
    let type = String(blob.type || '').split(';')[0].toLowerCase();
    if (!type) type = ({mp3:'audio/mpeg',m4a:'audio/mp4',aac:'audio/aac',wav:'audio/wav',ogg:'audio/ogg',opus:'audio/ogg',flac:'audio/flac',webm:'audio/webm'})[String(name).toLowerCase().split('.').pop()] || '';
    if (!TYPES.has(type)) throw new Error('只支持 MP3、M4A、AAC、WAV、OGG、FLAC 或 WebM 音频。');
    const bytes = new Uint8Array(await blob.slice(0, 80).arrayBuffer()), ascii = (start, size) => String.fromCharCode(...bytes.slice(start, start + size));
    if (!(ascii(0,3) === 'ID3' || bytes[0] === 255 && (bytes[1] & 224) === 224 || ascii(0,4) === 'RIFF' && ascii(8,4) === 'WAVE' || ascii(0,4) === 'OggS' || ascii(0,4) === 'fLaC' || ascii(4,4) === 'ftyp' || bytes[0] === 26 && bytes[1] === 69 && bytes[2] === 223 && bytes[3] === 163)) throw new Error('文件内容不是可识别的音频。');
    if (type === 'application/ogg') type = 'audio/ogg';
    return blob.type === type ? blob : new Blob([blob], {type});
  }
  function decode(record) {
    if (!TYPES.has(String(record.type || '').toLowerCase()) || typeof record.data !== 'string' || record.data.length > Math.ceil(originalAudio.MAX_FILE / 3) * 4 + 4 || !/^[A-Za-z0-9+/]*={0,2}$/.test(record.data)) throw new Error('备份中的音频格式无效或过大。');
    const bytes = host.atob(record.data); return new Blob([Uint8Array.from(bytes, char => char.charCodeAt(0))], {type:record.type});
  }
  async function encode(blob) { const bytes = new Uint8Array(await blob.arrayBuffer()); let data = ''; for (let i = 0; i < bytes.length; i += 16384) data += String.fromCharCode(...bytes.subarray(i, i + 16384)); return host.btoa(data); }
  function serialize(task) { const promise = mediaQueue.then(task, task); mediaQueue = promise.catch(() => {}); return promise; }
  async function store(records) {
    return serialize(async () => {
      const pending = new Map(media), mapping = Object.create(null), addedIds = [];
      for (const record of records) {
        const encoded = await encode(record.blob); let match;
        for (const item of pending.values()) if (item.blob.size === record.blob.size && await encode(item.blob) === encoded) { match = item; break; }
        if (match) { mapping[record.id] = match.id; pending.set(match.id, {...match,protectedUntil:Date.now()+300000}); continue; }
        let id = record.id; while (pending.has(id) || builtins().some(item => item.id === id)) id = freshId('media');
        pending.set(id, {...record,id,protectedUntil:Date.now()+300000}); mapping[record.id] = id; addedIds.push(id);
      }
      if ([...pending.values()].reduce((sum,item) => sum + item.blob.size, 0) > originalAudio.MAX_TOTAL) throw new Error('音频总量不能超过 150 MB。');
      media.clear(); for (const [id,record] of pending) media.set(id,record); audit.mediaWrites++;
      return {mapping,addedIds,count:records.length};
    });
  }
  async function importAudio(file) { const blob = await validateBlob(file,file?.name), id = freshId('media'), result = await store([{id,blob,name:text(file.name,200),addedAt:Date.now(),source:'用户导入的音频',license:'由导入者确认使用权限'}]); return result.mapping[id]; }
  async function restoreMedia(records) {
    if (!Array.isArray(records) || records.length > 2000) throw new Error('音频备份格式无效。');
    const ids = new Set(), validated = []; let bytes = 0;
    for (const record of records) {
      if (!record || typeof record.id !== 'string' || !/^[a-zA-Z0-9_-]{1,160}$/.test(record.id) || ids.has(record.id) || builtins().some(item => item.id === record.id)) throw new Error('音频备份包含无效、重复或保留的标识。');
      ids.add(record.id); const blob = await validateBlob(decode(record)); bytes += blob.size;
      if (bytes > originalAudio.MAX_TOTAL) throw new Error('音频备份不能超过 150 MB。');
      validated.push({id:record.id,blob,name:text(record.name,200),addedAt:Number(record.addedAt)||Date.now(),...metadata(record)});
    }
    return store(validated);
  }
  async function hasAudio(id) { audit.mediaReads++; return !!id && (media.has(id) || builtins().some(item => item.id === id)); }
  async function cacheAudio(context) {
    if (!context || context.type === 'tts') throw new Error('浏览器朗读不能缓存为录音。');
    requireRights(context); if (context.audioId && await hasAudio(context.audioId)) return context.audioId;
    const url = originalAudio.safeURL(context.audioUrl), controller = new AbortController(), timer = setTimeout(() => controller.abort(), 30000);
    try {
      const response = await host.fetch(url,{mode:'cors',credentials:'omit',redirect:'follow',signal:controller.signal,referrerPolicy:'no-referrer'});
      if (!response.ok) throw new Error('音频下载失败。'); if (response.url) originalAudio.safeURL(response.url);
      if (Number(response.headers.get('content-length')) > originalAudio.MAX_FILE) throw new Error('单个音频不能超过 15 MB。');
      const type = String(response.headers.get('content-type')||'').split(';')[0].trim().toLowerCase(); if (!TYPES.has(type)) throw new Error('服务器返回的内容不是音频。');
      let blob;
      if (response.body?.getReader) { const reader = response.body.getReader(), chunks = []; let total = 0; while (true) { const part = await reader.read(); if (part.done) break; total += part.value.byteLength; if (total > originalAudio.MAX_FILE) { await reader.cancel(); throw new Error('单个音频不能超过 15 MB。'); } chunks.push(part.value); } blob = new Blob(chunks,{type}); }
      else blob = await response.blob();
      blob = await validateBlob(blob); const id = freshId('cache'), result = await store([{id,blob,name:text(context.text,200),addedAt:Date.now(),audioUrl:url,...metadata(context)}]); return result.mapping[id];
    } finally { clearTimeout(timer); }
  }
  async function exportMedia(references) {
    audit.mediaReads++; const wanted = references === undefined ? null : new Set(references), out = [];
    for (const record of media.values()) { if (wanted && !wanted.has(record.id)) continue; const {blob,protectedUntil,...rest} = record; out.push({...rest,type:blob.type,data:await encode(blob)}); } return out;
  }
  async function storageStatus(references) {
    audit.mediaReads++; const records = [...media.values()], wanted = references === undefined ? null : new Set(references), unused = wanted ? records.filter(item => !wanted.has(item.id) && !(item.protectedUntil > Date.now())) : [];
    return {available:true,preview:true,backend:'memory',count:records.length,bytes:records.reduce((sum,item) => sum+item.blob.size,0),unusedCount:unused.length,unusedBytes:unused.reduce((sum,item) => sum+item.blob.size,0),maxBytes:originalAudio.MAX_TOTAL,maxFileBytes:originalAudio.MAX_FILE,builtinCount:builtins().length};
  }
  async function cleanupMedia(references) {
    if (typeof references !== 'function' && !Array.isArray(references) && !(references instanceof Set)) throw new Error('清理音频前需要核对保留的引用。');
    return serialize(async () => { const protectedIds = new Set(typeof references === 'function' ? await references() : references); let count = 0, bytes = 0; for (const item of media.values()) if (!protectedIds.has(item.id) && !(item.protectedUntil > Date.now())) { media.delete(item.id); count++; bytes += item.blob.size; } audit.mediaWrites++; return {count,bytes}; });
  }
  function stop() { if (mediaPlayback) mediaPlayback.finish('stopped'); originalAudio.stop(); }
  function speak(value, options) { stop(); return originalAudio.speak(value,options); }
  function play(context = {}, options = {}) {
    stop(); audit.mediaReads++;
    if (!context.audioId || builtins().some(item => item.id === context.audioId)) return originalAudio.play(context,options);
    const record = media.get(context.audioId);
    // Strip unknown IDs before delegating: original play must never read its DB.
    if (!record) return originalAudio.play({...context,audioId:''},options);
    if (context.type === 'tts') return originalAudio.speak(context.text,options);
    try { requireRights(context); } catch (error) { return originalAudio.speak(context.text,{...options,fallback:true,reason:error.message}); }
    const mode = context.type === 'original' ? 'original' : 'human', audio = new host.Audio(), url = URL.createObjectURL(record.blob);
    let resolve; const promise = new Promise(done => { resolve = done; });
    const emit = (state, extra = {}) => { const status = {state,mode,label:originalAudio.labelFor(mode),ok:!['error','stopped'].includes(state),...extra}; try { options.onStatus?.(status); } catch (_) {} return status; };
    const item = {dispose() { mediaPlayback = null; clearTimeout(item.timer); audio.onended = audio.onerror = null; audio.pause(); audio.removeAttribute('src'); audio.load(); URL.revokeObjectURL(url); },finish(state, extra) { if (mediaPlayback !== item) return; item.dispose(); resolve(emit(state,extra)); }};
    const fallback = reason => { if (mediaPlayback !== item) return; item.dispose(); originalAudio.speak(context.text,{...options,fallback:true,reason}).then(resolve); };
    mediaPlayback = item; audio.preload = 'none'; audio.src = url; audio.playbackRate = Math.min(1.5,Math.max(.5,Number(options.rate)||1)); audio.onended = () => item.finish('ended'); audio.onerror = () => fallback('音频不可用，已改用合成朗读。');
    emit('loading'); if (mediaPlayback !== item) return promise;
    item.timer = setTimeout(() => fallback('音频加载超时。'),20000);
    Promise.resolve().then(() => mediaPlayback === item ? audio.play() : undefined).then(() => { if (mediaPlayback === item) {clearTimeout(item.timer);emit('playing');} }, error => { if (error?.name === 'NotAllowedError') item.finish('error',{error:'浏览器暂停了声音，请再次点击播放。'}); else fallback('音频不可用，已改用合成朗读。'); });
    return promise;
  }
  host.AudioKit = Object.freeze({...originalAudio,stop,speak,play,importAudio,hasAudio,cacheAudio,exportMedia,restoreMedia,importMedia:async records => (await restoreMedia(records)).count,storageStatus,cleanupMedia,removeAudio:async id => { if (builtins().some(item => item.id === id)) throw new Error('内置示范音频无需单独删除。'); return serialize(() => {media.delete(id);audit.mediaWrites++;}); }});
  host.addEventListener('pagehide',stop);
  const preview = {
    ready,
    async showApp(view = 'today') { if (!['today','study','spelling','library','contexts','settings'].includes(view)) throw new Error('未知预览页面。'); await ready; return app.previewNavigate(view); },
    setAppearance(patch = {}) { const run = async () => { await ready; const current = preview.getAppearance(), next = {...current,...patch}; if (!['classic','atelier','verdure'].includes(next.design) || !['light','dark','system'].includes(next.mode) || !['immersive','standard','reduced','system'].includes(next.motion)) throw new Error('外观设置无效。'); const ok = await app.previewAppearance(next); if (ok) motion = next.motion; return ok; }; const operation = appearanceQueue.then(run,run); appearanceQueue = operation.catch(() => {}); return operation; },
    getSettings() { return app?.getSettings?.() || app?.getState?.()?.settings || copy(memory.settings); },
    getAppearance() { const settings = preview.getSettings(); return {design:settings.designTheme,mode:settings.theme,motion}; },
    getOriginalState:() => copy(originalFixture),
    getAudit:() => ({...audit,realDataLoaded:false,keysUnchanged:host.VocabData.KEY === originalData.KEY && host.VocabData.DB_NAME === originalData.DB_NAME,memoryRevision:memory.revision}),
    _attachApp(value) { app = value; resolveReady(preview); },
    _setMotion(value) { motion = value; }
  };
  host.VocabCarnetPreview = Object.freeze(preview);
})(window);
